import { useState } from "react";
import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Link } from "wouter";
import { ArrowLeft, Scale, FileText, ExternalLink, Calendar, Building2, Search, Loader2, Sparkles, Settings } from "lucide-react";
import { useActiveCase } from "@/contexts/CaseContext";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Slider } from "@/components/ui/slider";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { useMutation } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";

interface VectorSearchResult {
  id: string;
  score: number;
  ecli: string;
  title?: string;
  court?: string;
  decision_date?: string;
  legal_area?: string;
  procedure_type?: string;
  source_url?: string;
  text?: string;
  ai_feiten?: string;
  ai_geschil?: string;
  ai_beslissing?: string;
  ai_motivering?: string;
  ai_inhoudsindicatie?: string;
}

// Helper function to determine court rank (lower = higher authority)
function getCourtRank(courtName: string | undefined): number {
  if (!courtName) return 99; // Unknown courts have lowest priority
  
  const normalized = courtName.toLowerCase().trim();
  
  // Hoge Raad (highest authority) - handles "HR", "HR:", "Hoge Raad", etc.
  if (/\bhr\b/.test(normalized) || normalized.includes('hoge raad')) {
    return 0;
  }
  
  // Gerechtshof (court of appeal) - handles "Hof Amsterdam", "Gerechtshof", etc.
  if (/^hof\b/.test(normalized) || normalized.includes('gerechtshof') || /\bhof\s/.test(normalized)) {
    return 1;
  }
  
  // Rechtbank (district court)
  if (normalized.includes('rechtbank') || /\brb\b/.test(normalized)) {
    return 2;
  }
  
  // Unknown or other courts
  return 99;
}

// Re-rank results considering court hierarchy when scores are close (< 3% difference)
function applyCourtAwareRanking(results: VectorSearchResult[]): VectorSearchResult[] {
  return [...results].sort((a, b) => {
    const scoreA = a.score || 0;
    const scoreB = b.score || 0;
    const scoreDiff = Math.abs(scoreA - scoreB);
    
    // If scores differ by 3% or more, keep original Pinecone ordering (higher score first)
    if (scoreDiff >= 0.03) {
      return scoreB - scoreA; // Higher score first
    }
    
    // Scores are close (< 3% difference), prioritize higher court
    const rankA = getCourtRank(a.court);
    const rankB = getCourtRank(b.court);
    
    if (rankA !== rankB) {
      return rankA - rankB; // Lower rank number = higher authority = comes first
    }
    
    // Same court level, fall back to score
    return scoreB - scoreA;
  });
}

export default function Jurisprudentie() {
  const { isLoading: authLoading } = useAuth();
  const currentCase = useActiveCase();
  const { toast } = useToast();
  
  const [searchQuery, setSearchQuery] = useState("");
  const [legalArea, setLegalArea] = useState<string | undefined>(undefined);
  const [court, setCourt] = useState<string | undefined>(undefined);
  const [procedureType, setProcedureType] = useState<string | undefined>(undefined);
  const [results, setResults] = useState<VectorSearchResult[]>([]);
  const [autoGeneratedQuery, setAutoGeneratedQuery] = useState("");
  const [expandedResult, setExpandedResult] = useState<string | null>(null);
  
  // Advanced search settings
  const [topK, setTopK] = useState(20);
  const [scoreThreshold, setScoreThreshold] = useState(0.10); // 10% minimum for quality results
  const [showAdvancedSettings, setShowAdvancedSettings] = useState(false);
  const [maxResults, setMaxResults] = useState<number | null>(null); // Limit displayed results
  const [requiredKeywords, setRequiredKeywords] = useState(""); // Must-contain keywords
  const [searchIterations, setSearchIterations] = useState<string[]>([]); // Track search iterations

  const generateQueryMutation = useMutation({
    mutationFn: async () => {
      const response = await apiRequest('POST', '/api/pinecone/generate-query', {
        caseId: currentCase?.id
      });
      return response.json();
    },
    onSuccess: (data: any) => {
      setAutoGeneratedQuery(data.query);
      setSearchQuery(data.query);
      
      // Reset threshold to 30% for AI-generated queries (smart search will adjust)
      setScoreThreshold(0.30);
      
      // Set required keywords if generated by AI
      if (data.requiredKeywords && Array.isArray(data.requiredKeywords) && data.requiredKeywords.length > 0) {
        setRequiredKeywords(data.requiredKeywords.join(', '));
        toast({
          title: "AI zoekvraag en verplichte woorden gegenereerd",
          description: `Zoekvraag, ${data.requiredKeywords.length} verplichte ${data.requiredKeywords.length === 1 ? 'woord' : 'woorden'} ingesteld. Slimme zoekstrategie begint bij 30% relevantie`,
        });
      } else {
        toast({
          title: "AI zoekvraag gegenereerd",
          description: "Zoekvraag ingesteld. Slimme zoekstrategie begint bij 30% relevantie en past zich automatisch aan",
        });
      }
    },
    onError: (error: any) => {
      toast({
        title: "Fout bij genereren",
        description: error.message || "Kon geen zoekvraag genereren",
        variant: "destructive",
      });
    }
  });

  // Helper function to perform a single search with given parameters
  const performSearch = async (threshold: number, keywords: string[]): Promise<VectorSearchResult[]> => {
    const filters: Record<string, any> = {};
    
    if (legalArea) filters.legal_area = { $eq: legalArea };
    if (court) filters.court = { $eq: court };
    if (procedureType) filters.procedure_type = { $eq: procedureType };

    const response = await apiRequest('POST', '/api/pinecone/search', {
      query: searchQuery,
      filters: Object.keys(filters).length > 0 ? filters : undefined,
      topK: topK,
      scoreThreshold: threshold
    });
    
    const data = await response.json();
    let filteredResults = data.results || [];
    
    // Apply required keywords filter (case-insensitive)
    if (keywords.length > 0) {
      filteredResults = filteredResults.filter((result: VectorSearchResult) => {
        const searchText = [
          result.text,
          result.ai_inhoudsindicatie,
          result.ai_feiten,
          result.ai_geschil,
          result.ai_beslissing,
          result.ai_motivering,
          result.title
        ].join(' ').toLowerCase();
        
        // All keywords must be present
        return keywords.every(keyword => searchText.includes(keyword));
      });
    }
    
    return filteredResults;
  };

  const searchMutation = useMutation({
    mutationFn: async () => {
      const iterations: string[] = [];
      const allKeywords = requiredKeywords.trim() 
        ? requiredKeywords.toLowerCase().split(',').map(k => k.trim()).filter(k => k)
        : [];
      
      // Strategy: Start with highest quality (30%), progressively relax to 10%
      // This ensures the best matches appear first
      const thresholds = [0.30, 0.25, 0.20, 0.15, 0.10];
      
      // Step 1: Try with maximum threshold (30%) and all keywords
      let currentThreshold = thresholds[0];
      let currentKeywords = [...allKeywords];
      let results: VectorSearchResult[] = [];
      
      // Try different thresholds - starting high for best quality
      for (let i = 0; i < thresholds.length; i++) {
        currentThreshold = thresholds[i];
        results = await performSearch(currentThreshold, currentKeywords);
        
        const keywordText = currentKeywords.length > 0 
          ? ` met ${currentKeywords.length} verplichte ${currentKeywords.length === 1 ? 'woord' : 'woorden'}`
          : ' zonder verplichte woorden';
        
        iterations.push(`Poging ${i + 1}: ${(currentThreshold * 100).toFixed(0)}% relevantiedrempel${keywordText} → ${results.length} resultaten`);
        
        // If we have at least 5 results, we're done
        if (results.length >= 5) {
          break;
        }
      }
      
      // Step 2: If still less than 5 results, remove keywords one by one
      if (results.length < 5 && currentKeywords.length > 0) {
        currentThreshold = 0.10; // Use minimum threshold
        
        while (currentKeywords.length > 0 && results.length < 5) {
          currentKeywords.pop(); // Remove last keyword
          results = await performSearch(currentThreshold, currentKeywords);
          
          const keywordText = currentKeywords.length > 0 
            ? ` met ${currentKeywords.length} verplichte ${currentKeywords.length === 1 ? 'woord' : 'woorden'}`
            : ' zonder verplichte woorden';
          
          iterations.push(`Extra poging: 10% relevantiedrempel${keywordText} → ${results.length} resultaten`);
          
          if (results.length >= 5) {
            break;
          }
        }
      }
      
      // Apply court-aware re-ranking before slicing
      // This ensures higher courts (HR, Hof) appear first when scores are close (< 3%)
      const rankedResults = applyCourtAwareRanking(results);
      
      return { 
        results: rankedResults.slice(0, 10), // Max 10 results
        iterations,
        finalThreshold: currentThreshold,
        finalKeywords: currentKeywords
      };
    },
    onSuccess: (data: any) => {
      setResults(data.results);
      setSearchIterations(data.iterations || []);
      
      const resultCount = data.results.length;
      const iterationCount = data.iterations.length;
      
      toast({
        title: "Slimme zoekstrategie voltooid",
        description: `${resultCount} resultaten gevonden na ${iterationCount} ${iterationCount === 1 ? 'poging' : 'pogingen'}. Top 10 getoond.`,
      });
    },
    onError: (error: any) => {
      toast({
        title: "Fout bij zoeken",
        description: error.message || "Kon niet zoeken in database",
        variant: "destructive",
      });
    }
  });

  const handleSearch = () => {
    if (!searchQuery.trim()) {
      toast({
        title: "Geen zoekvraag",
        description: "Voer een zoekvraag in om te zoeken",
        variant: "destructive",
      });
      return;
    }
    
    // Clear previous results and iterations before starting new search
    setResults([]);
    setSearchIterations([]);
    
    searchMutation.mutate();
  };

  if (authLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto"></div>
          <p className="mt-4 text-muted-foreground">Laden...</p>
        </div>
      </div>
    );
  }

  if (!currentCase) {
    return (
      <div className="text-center py-12">
        <div className="max-w-md mx-auto">
          <h2 className="text-2xl font-bold text-foreground mb-4">Geen actieve zaak</h2>
          <p className="text-muted-foreground mb-6">
            U heeft nog geen zaak aangemaakt.
          </p>
          <Button asChild size="lg" data-testid="button-create-first-case">
            <Link href="/new-case">
              Eerste zaak starten
            </Link>
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8">
      <Button variant="ghost" asChild className="mb-4" data-testid="button-back-to-analysis">
        <Link href="/analysis">
          <ArrowLeft className="mr-2 h-4 w-4" />
          Terug naar analyse
        </Link>
      </Button>

      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">Jurisprudentie</h1>
        <p className="text-muted-foreground">
          Zoek relevante rechterlijke uitspraken voor {currentCase.title || 'uw zaak'}
        </p>
      </div>

      {/* Search form */}
      <Card className="mb-6" data-testid="card-search-filters">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5" />
            Semantisch zoeken in jurisprudentie
          </CardTitle>
          <CardDescription>
            Doorzoek de volledige tekst van Nederlandse rechterlijke uitspraken met AI-powered semantische zoekopdrachten
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div>
              <Label htmlFor="searchQuery">Zoekvraag</Label>
              <Input 
                id="searchQuery"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Bijvoorbeeld: ontbinding huurovereenkomst wegens geluidsoverlast"
                data-testid="input-search-query"
                onKeyPress={(e) => {
                  if (e.key === 'Enter') {
                    handleSearch();
                  }
                }}
                className="text-base"
              />
              <p className="text-xs text-muted-foreground mt-1">
                Beschrijf uw juridische vraag in natuurlijke taal
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <Label htmlFor="legal-area">Rechtsgebied (optioneel)</Label>
                <Select value={legalArea} onValueChange={(value) => setLegalArea(value === "all" ? undefined : value)}>
                  <SelectTrigger id="legal-area" data-testid="select-legal-area">
                    <SelectValue placeholder="Alle rechtsgebieden" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">Alle rechtsgebieden</SelectItem>
                    <SelectItem value="Civiel recht">Civiel recht</SelectItem>
                    <SelectItem value="Bestuursrecht">Bestuursrecht</SelectItem>
                    <SelectItem value="Strafrecht">Strafrecht</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label htmlFor="court">Rechtbank (optioneel)</Label>
                <Select value={court} onValueChange={(value) => setCourt(value === "all" ? undefined : value)}>
                  <SelectTrigger id="court" data-testid="select-court">
                    <SelectValue placeholder="Alle rechtbanken" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">Alle rechtbanken</SelectItem>
                    <SelectItem value="Hoge Raad">Hoge Raad</SelectItem>
                    <SelectItem value="Rechtbank Amsterdam">Rechtbank Amsterdam</SelectItem>
                    <SelectItem value="Rechtbank Rotterdam">Rechtbank Rotterdam</SelectItem>
                    <SelectItem value="Rechtbank Den Haag">Rechtbank Den Haag</SelectItem>
                    <SelectItem value="Rechtbank Utrecht">Rechtbank Utrecht</SelectItem>
                    <SelectItem value="Gerechtshof Amsterdam">Gerechtshof Amsterdam</SelectItem>
                    <SelectItem value="Gerechtshof Den Haag">Gerechtshof Den Haag</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label htmlFor="procedure-type">Procedure type (optioneel)</Label>
                <Select value={procedureType} onValueChange={(value) => setProcedureType(value === "all" ? undefined : value)}>
                  <SelectTrigger id="procedure-type" data-testid="select-procedure-type">
                    <SelectValue placeholder="Alle procedures" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">Alle procedures</SelectItem>
                    <SelectItem value="Bodemzaak">Bodemzaak</SelectItem>
                    <SelectItem value="Kort geding">Kort geding</SelectItem>
                    <SelectItem value="Hoger beroep">Hoger beroep</SelectItem>
                    <SelectItem value="Cassatie">Cassatie</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            {/* Advanced Settings */}
            <Collapsible open={showAdvancedSettings} onOpenChange={setShowAdvancedSettings}>
              <CollapsibleTrigger asChild>
                <Button 
                  variant="outline" 
                  className="w-full md:w-auto gap-2"
                  data-testid="button-toggle-advanced-settings"
                >
                  <Settings className="h-4 w-4" />
                  Geavanceerde instellingen
                  <span className="text-xs text-muted-foreground ml-2">
                    ({showAdvancedSettings ? 'verbergen' : 'tonen'})
                  </span>
                </Button>
              </CollapsibleTrigger>
              <CollapsibleContent className="mt-4 space-y-6">
                <div className="border rounded-lg p-4 bg-muted/30 space-y-4">
                  <div className="space-y-3">
                    <div className="flex items-center justify-between">
                      <Label htmlFor="topK" className="font-semibold">Maximum aantal resultaten</Label>
                      <span className="text-sm font-mono bg-primary/10 px-2 py-1 rounded">{topK}</span>
                    </div>
                    <Slider
                      id="topK"
                      min={5}
                      max={50}
                      step={5}
                      value={[topK]}
                      onValueChange={(value) => setTopK(value[0])}
                      data-testid="slider-topk"
                      className="w-full"
                    />
                    <p className="text-xs text-muted-foreground">
                      Beperk het aantal resultaten dat Pinecone retourneert (5-50)
                    </p>
                  </div>

                  <div className="space-y-3">
                    <div className="flex items-center justify-between">
                      <Label htmlFor="scoreThreshold" className="font-semibold">Relevantie drempel (score)</Label>
                      <span className="text-sm font-mono bg-primary/10 px-2 py-1 rounded">{(scoreThreshold * 100).toFixed(1)}%</span>
                    </div>
                    <Slider
                      id="scoreThreshold"
                      min={0.10}
                      max={0.30}
                      step={0.01}
                      value={[scoreThreshold]}
                      onValueChange={(value) => setScoreThreshold(value[0])}
                      data-testid="slider-score-threshold"
                      className="w-full"
                      disabled={!!autoGeneratedQuery}
                    />
                    {autoGeneratedQuery ? (
                      <p className="text-xs text-amber-600 dark:text-amber-400 flex items-center gap-1">
                        <Sparkles className="h-3 w-3" />
                        Bij AI-gegenereerde zoekopdrachten bepaalt de slimme zoekstrategie automatisch de optimale drempelwaarde (start bij 30%, past zich aan tot 10%)
                      </p>
                    ) : (
                      <p className="text-xs text-muted-foreground">
                        Minimale similarity score voor resultaten. Hogere waarde = strengere filtering (10% - 30%)
                      </p>
                    )}
                  </div>

                  <div className="space-y-3">
                    <div className="flex items-center justify-between">
                      <Label htmlFor="maxResults" className="font-semibold">Toon alleen top resultaten</Label>
                      <span className="text-sm font-mono bg-primary/10 px-2 py-1 rounded">
                        {maxResults || 'alle'}
                      </span>
                    </div>
                    <div className="flex gap-2 flex-wrap">
                      <Button
                        variant={maxResults === null ? "default" : "outline"}
                        size="sm"
                        onClick={() => setMaxResults(null)}
                        data-testid="button-show-all"
                      >
                        Alle
                      </Button>
                      <Button
                        variant={maxResults === 3 ? "default" : "outline"}
                        size="sm"
                        onClick={() => setMaxResults(3)}
                        data-testid="button-show-top3"
                      >
                        Top 3
                      </Button>
                      <Button
                        variant={maxResults === 5 ? "default" : "outline"}
                        size="sm"
                        onClick={() => setMaxResults(5)}
                        data-testid="button-show-top5"
                      >
                        Top 5
                      </Button>
                      <Button
                        variant={maxResults === 10 ? "default" : "outline"}
                        size="sm"
                        onClick={() => setMaxResults(10)}
                        data-testid="button-show-top10"
                      >
                        Top 10
                      </Button>
                    </div>
                    <p className="text-xs text-muted-foreground">
                      Beperk weergave tot alleen de meest relevante resultaten
                    </p>
                  </div>

                  <div className="space-y-3">
                    <Label htmlFor="requiredKeywords" className="font-semibold">
                      Verplichte woorden (exact match)
                      <span className="ml-2 text-xs font-normal text-muted-foreground">(optioneel)</span>
                    </Label>
                    <Input
                      id="requiredKeywords"
                      value={requiredKeywords}
                      onChange={(e) => setRequiredKeywords(e.target.value)}
                      placeholder='Bijvoorbeeld: huurovereenkomst, merkinbreuk'
                      data-testid="input-required-keywords"
                      className="text-sm"
                    />
                    <p className="text-xs text-muted-foreground">
                      Alleen resultaten die deze woorden bevatten worden getoond. Scheid meerdere woorden met een komma. Hoofdletter-ongevoelig. Bij automatisch zoeken worden deze woorden door AI gegenereerd.
                    </p>
                  </div>

                  <div className="bg-blue-50 dark:bg-blue-950/30 border border-blue-200 dark:border-blue-800 rounded p-3 space-y-2">
                    <p className="text-xs text-blue-900 dark:text-blue-100">
                      <strong>💡 Tip:</strong> De slimme zoekstrategie begint met 30% relevantiedrempel (hoogste kwaliteit) en past zich automatisch aan tot 10% voor bredere resultaten. Gebruik "Verplichte woorden" voor exacte termen (bijv. bedrijfsnamen, artikel nummers).
                    </p>
                    <p className="text-xs text-blue-900 dark:text-blue-100">
                      <strong>⚖️ Rechtshiërarchie:</strong> Resultaten worden gesorteerd op relevantie, maar bij vergelijkbare scores (verschil &lt;3%) krijgen hogere rechters voorrang: Hoge Raad &gt; Gerechtshof &gt; Rechtbank.
                    </p>
                  </div>
                </div>
              </CollapsibleContent>
            </Collapsible>

            <Button 
              onClick={handleSearch} 
              disabled={searchMutation.isPending || !searchQuery.trim()}
              data-testid="button-search"
              className="w-full md:w-auto"
              size="lg"
            >
              {searchMutation.isPending ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Zoeken...
                </>
              ) : (
                <>
                  <Search className="mr-2 h-4 w-4" />
                  Zoeken in jurisprudentie
                </>
              )}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Automatic Jurisprudence Search */}
      <Card className="mb-6" data-testid="card-auto-search">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary" />
            Automatische Jurisprudentie Zoekopdracht
          </CardTitle>
          <CardDescription>
            Laat AI een geoptimaliseerde zoekvraag genereren op basis van uw volledige juridisch advies om relevante rechtspraak te vinden die uw rechtspositie versterkt
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="bg-primary/5 border border-primary/20 rounded-lg p-4">
              <div className="flex items-start gap-3 mb-3">
                <Sparkles className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                <div className="flex-1">
                  <h4 className="font-semibold text-sm mb-1">Hoe werkt dit?</h4>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    AI analyseert uw juridisch advies (feiten, geschil, juridische duiding) en genereert een geoptimaliseerde zoekopdracht 
                    die specifiek gericht is op het vinden van jurisprudentie die uw rechtspositie ondersteunt en uw kans op succes vergroot.
                  </p>
                </div>
              </div>
            </div>

            <div>
              <Label htmlFor="autoQuery">AI-gegenereerde zoekvraag</Label>
              <div className="flex gap-2">
                <Input 
                  id="autoQuery"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder="Klik op 'Genereer Zoekvraag' om AI een optimale zoekvraag te laten maken"
                  data-testid="input-auto-query"
                  className="text-base flex-1"
                  onKeyPress={(e) => {
                    if (e.key === 'Enter' && searchQuery.trim()) {
                      handleSearch();
                    }
                  }}
                />
                <Button
                  onClick={() => generateQueryMutation.mutate()}
                  disabled={generateQueryMutation.isPending || !currentCase}
                  data-testid="button-generate-query"
                  variant="secondary"
                  size="lg"
                >
                  {generateQueryMutation.isPending ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Genereren...
                    </>
                  ) : (
                    <>
                      <Sparkles className="mr-2 h-4 w-4" />
                      Genereer Zoekvraag
                    </>
                  )}
                </Button>
              </div>
              <p className="text-xs text-muted-foreground mt-1">
                De AI analyseert uw juridisch advies en stelt automatisch de meest effectieve zoekvraag, verplichte kernwoorden én relevantiedrempel (10%) in
              </p>
              
              {/* Show active AI settings */}
              {autoGeneratedQuery && (
                <div className="mt-3 p-3 bg-primary/5 border border-primary/10 rounded-lg">
                  <div className="flex items-start gap-2">
                    <Sparkles className="h-4 w-4 text-primary mt-0.5 flex-shrink-0" />
                    <div className="flex-1 space-y-2">
                      <div>
                        <p className="text-xs font-semibold text-primary">Actieve AI-instellingen:</p>
                      </div>
                      <div className="space-y-1 text-xs">
                        <div className="flex items-start gap-2">
                          <span className="font-medium text-muted-foreground">Zoekvraag:</span>
                          <span className="flex-1">{searchQuery}</span>
                        </div>
                        {requiredKeywords && (
                          <div className="flex items-start gap-2">
                            <span className="font-medium text-muted-foreground">Verplichte woorden:</span>
                            <span className="flex-1 font-mono text-primary">{requiredKeywords}</span>
                          </div>
                        )}
                        <div className="flex items-start gap-2">
                          <span className="font-medium text-muted-foreground">Relevantiedrempel:</span>
                          <span className="font-mono text-primary">{(scoreThreshold * 100).toFixed(0)}%</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </div>

            {searchQuery.trim() && (
              <Button 
                onClick={handleSearch} 
                disabled={searchMutation.isPending}
                data-testid="button-auto-search"
                className="w-full"
                size="lg"
              >
                {searchMutation.isPending ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Zoeken...
                  </>
                ) : (
                  <>
                    <Search className="mr-2 h-4 w-4" />
                    Zoeken met deze vraag
                  </>
                )}
              </Button>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Search Iterations - Show what the smart search did */}
      {searchIterations.length > 0 && (
        <Card className="mb-6 bg-primary/5 border-primary/20">
          <CardHeader>
            <CardTitle className="text-base flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-primary" />
              Slimme zoekstrategie
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {searchIterations.map((iteration, index) => (
                <div key={index} className="flex items-start gap-2 text-sm">
                  <span className="text-primary font-mono min-w-[20px]">{index + 1}.</span>
                  <span className="text-muted-foreground">{iteration}</span>
                </div>
              ))}
            </div>
            <div className="mt-3 pt-3 border-t space-y-2">
              <p className="text-xs text-muted-foreground">
                De slimme zoekstrategie begint met de hoogste kwaliteit (30%) en past zich automatisch aan voor optimale resultaten
              </p>
              <div className="flex items-start gap-2 bg-blue-50 dark:bg-blue-950/30 border border-blue-200 dark:border-blue-800 rounded p-2">
                <Scale className="h-3 w-3 text-blue-600 dark:text-blue-400 mt-0.5 flex-shrink-0" />
                <p className="text-xs text-blue-900 dark:text-blue-100">
                  <strong>Rechtshiërarchie:</strong> Bij vergelijkbare scores (verschil &lt;3%) worden uitspraken van hogere rechters (Hoge Raad → Gerechtshof → Rechtbank) eerst getoond
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Results */}
      {results.length > 0 && (
        <div className="mb-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-xl font-semibold flex items-center gap-2">
              <Sparkles className="h-5 w-5" />
              {maxResults && results.length > maxResults 
                ? `${maxResults} van ${results.length} uitspraken getoond (top resultaten)`
                : `${results.length} relevante ${results.length === 1 ? 'uitspraak' : 'uitspraken'} gevonden`
              }
            </h2>
          </div>

          <div className="space-y-4">
            {(maxResults ? results.slice(0, maxResults) : results).map((result, index) => (
              <Card key={result.id} data-testid={`card-result-${index}`}>
                <CardHeader>
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex-1">
                      <CardTitle className="text-lg mb-2">
                        {result.title || result.ecli}
                      </CardTitle>
                      <div className="flex flex-wrap gap-2 mb-2">
                        {result.court && (
                          <Badge variant="secondary" className="text-xs">
                            <Building2 className="h-3 w-3 mr-1" />
                            {result.court}
                          </Badge>
                        )}
                        {result.decision_date && (
                          <Badge variant="outline" className="text-xs">
                            <Calendar className="h-3 w-3 mr-1" />
                            {result.decision_date}
                          </Badge>
                        )}
                        {result.legal_area && (
                          <Badge variant="outline" className="text-xs">
                            <Scale className="h-3 w-3 mr-1" />
                            {result.legal_area}
                          </Badge>
                        )}
                        {result.procedure_type && (
                          <Badge variant="outline" className="text-xs">
                            {result.procedure_type}
                          </Badge>
                        )}
                      </div>
                      <p className="text-xs text-muted-foreground font-mono">
                        {result.ecli}
                      </p>
                    </div>
                    {result.source_url && (
                      <Button 
                        variant="outline" 
                        size="sm" 
                        asChild
                        data-testid={`button-view-${index}`}
                      >
                        <a 
                          href={result.source_url} 
                          target="_blank" 
                          rel="noopener noreferrer"
                        >
                          <ExternalLink className="h-4 w-4 mr-2" />
                          Bekijk op Rechtspraak.nl
                        </a>
                      </Button>
                    )}
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    {/* Relevantie Score */}
                    <div className="flex items-center gap-2 text-sm">
                      <Badge variant="secondary" className="text-xs" data-testid={`badge-score-${index}`}>
                        Relevantie: {(result.score * 100).toFixed(1)}%
                      </Badge>
                    </div>

                    {/* Tekst uit Pinecone record */}
                    {result.text && (
                      <div className="bg-muted/30 p-4 rounded-lg border" data-testid={`section-text-${index}`}>
                        <div className="flex items-center gap-2 mb-3">
                          <FileText className="h-4 w-4 text-foreground" />
                          <h4 className="font-semibold text-sm">Uitspraak tekst</h4>
                        </div>
                        <div className="prose prose-sm max-w-none text-sm">
                          <p className="text-foreground whitespace-pre-wrap leading-relaxed" data-testid={`text-content-${index}`}>
                            {result.text}
                          </p>
                        </div>
                      </div>
                    )}

                    {/* AI Samenvatting */}
                    {(result.ai_inhoudsindicatie || result.ai_feiten || result.ai_geschil || result.ai_beslissing || result.ai_motivering) && (
                      <div className="bg-primary/5 p-4 rounded-lg border border-primary/10">
                        <div className="flex items-center gap-2 mb-3">
                          <Sparkles className="h-4 w-4 text-primary" />
                          <h4 className="font-semibold text-sm">AI Samenvatting</h4>
                        </div>
                        <div className="prose prose-sm max-w-none text-sm">
                          {expandedResult === result.id ? (
                            // Show full summary
                            <div className="space-y-4">
                              {result.ai_inhoudsindicatie && (
                                <div>
                                  <h5 className="font-semibold mb-1">Inhoudsindicatie</h5>
                                  <p className="text-muted-foreground whitespace-pre-wrap leading-relaxed">
                                    {result.ai_inhoudsindicatie}
                                  </p>
                                </div>
                              )}
                              {result.ai_feiten && (
                                <div>
                                  <h5 className="font-semibold mb-1">Feiten</h5>
                                  <p className="text-muted-foreground whitespace-pre-wrap leading-relaxed">
                                    {result.ai_feiten}
                                  </p>
                                </div>
                              )}
                              {result.ai_geschil && (
                                <div>
                                  <h5 className="font-semibold mb-1">Geschil</h5>
                                  <p className="text-muted-foreground whitespace-pre-wrap leading-relaxed">
                                    {result.ai_geschil}
                                  </p>
                                </div>
                              )}
                              {result.ai_beslissing && (
                                <div>
                                  <h5 className="font-semibold mb-1">Beslissing</h5>
                                  <p className="text-muted-foreground whitespace-pre-wrap leading-relaxed">
                                    {result.ai_beslissing}
                                  </p>
                                </div>
                              )}
                              {result.ai_motivering && (
                                <div>
                                  <h5 className="font-semibold mb-1">Motivering</h5>
                                  <p className="text-muted-foreground whitespace-pre-wrap leading-relaxed">
                                    {result.ai_motivering}
                                  </p>
                                </div>
                              )}
                              <Button
                                variant="link"
                                size="sm"
                                className="p-0 h-auto text-primary"
                                onClick={() => setExpandedResult(null)}
                                data-testid={`button-collapse-${index}`}
                              >
                                Minder tonen
                              </Button>
                            </div>
                          ) : (
                            // Show first 2 lines
                            <div>
                              {(() => {
                                const fullText = [
                                  result.ai_inhoudsindicatie,
                                  result.ai_feiten,
                                  result.ai_geschil,
                                  result.ai_beslissing,
                                  result.ai_motivering
                                ].filter(Boolean).join('\n\n');
                                
                                const lines = fullText.split('\n').filter(l => l.trim());
                                const preview = lines.slice(0, 2).join('\n');
                                
                                return (
                                  <>
                                    <p className="text-muted-foreground whitespace-pre-wrap leading-relaxed">
                                      {preview}
                                    </p>
                                    {lines.length > 2 && (
                                      <Button
                                        variant="link"
                                        size="sm"
                                        className="p-0 h-auto text-primary mt-2"
                                        onClick={() => setExpandedResult(result.id)}
                                        data-testid={`button-expand-${index}`}
                                      >
                                        Verder lezen →
                                      </Button>
                                    )}
                                  </>
                                );
                              })()}
                            </div>
                          )}
                        </div>
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      )}

      {!results.length && !searchMutation.isPending && (
        <Card data-testid="card-jurisprudentie-empty">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Scale className="h-5 w-5" />
              Zoeken in jurisprudentie
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-center py-12">
              <FileText className="h-16 w-16 text-muted-foreground mx-auto mb-4" />
              <h3 className="text-xl font-semibold mb-2">Nog geen jurisprudentie gezocht</h3>
              <p className="text-sm text-muted-foreground max-w-md mx-auto">
                Gebruik de zoekopdracht hierboven om relevante rechterlijke uitspraken te vinden met AI-powered semantische zoekopdrachten.
              </p>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
